#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
- name: Install nginx
  ansible.builtin.apt: #ansible builtin apt package module to install the packages for debian based system
    name: nginx
    state: present #check for the package and install it
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html #source file
    dest: /var/www/html #destination file path
    owner: root #setting the owner of the file
    group: root
    mode: '0644' #setting the permissions of the file
